default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  host: localhost

development:
  <<: *default
  database: read_hadoop_development

test:
  <<: *default
  database: read_hadoop_test

production:
  <<: *default
  database: read_hadoop_production
  username: read_hadoop
  password: <%= ENV['READ_HADOOP_DATABASE_PASSWORD'] %>
